language: java
jdk:
  - oraclejdk8
script:
    - echo "Hola travis"
    - mvn package
    - chmod 400 intancia.pem
    - ssh-keyscan -H 3.135.128.20 >> ~/.ssh/known_hosts
    - ssh-keyscan -H ec2-3-135-128-20.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts
    - scp -i instancia.pem target/Netflix-1.0-SNAPSHOT.war ubuntu@3.135.128.20:/tmp
